# Generated by Django 3.2.8 on 2021-10-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
