# Generated by Django 3.2.8 on 2021-10-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.CharField(default='example@example.ru', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(default='7962123457', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='retailer_fio',
            field=models.CharField(default='Bob Bob Bob', max_length=200),
            preserve_default=False,
        ),
    ]
