# Generated by Django 3.2.8 on 2021-10-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kupon', '0002_auto_20211020_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='retailer_fio',
            new_name='retailer',
        ),
    ]
