# Generated by Django 3.2.8 on 2021-10-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kupon', '0003_rename_retailer_fio_organization_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='client_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offer',
            name='quantity_per_hand',
            field=models.IntegerField(default=1),
        ),
    ]
