# Generated by Django 3.2.8 on 2021-11-12 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kupon', '0005_auto_20211101_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kupon.offer')),
            ],
            options={
                'db_table': 'offer_address',
            },
        ),
    ]
