# Generated by Django 3.2.8 on 2021-11-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kupon', '0006_offeraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offeraddress',
            old_name='address',
            new_name='name',
        ),
        migrations.AddField(
            model_name='offeraddress',
            name='latitude',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='offeraddress',
            name='longitude',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
