# Generated by Django 3.2.8 on 2021-11-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kupon', '0007_auto_20211115_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='date_activate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='date_buy',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
