# Generated by Django 3.2.8 on 2021-11-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kupon', '0009_organization_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
